- name: quarto exemplo de ansible
  hosts: virsh
  gather_facts: false

  tasks:
    - name: pegando o nome da maquina
      command: hostname
      delegate_to: localhost
      register: result
    - debug: var=result.stdout
    - name: usando jinja2 pra templating
      command: "echo \"{{ variavel }}\""
      delegate_to: localhost
      register: result
    - debug: var=result.stdout
    - debug: var=variavel
      
